# Generated by Django 4.2.29 on 2026-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joblog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="joblog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="joblog",
            index=models.Index(
                fields=["job", "-timestamp"], name="jobs_joblog_job_id_6883b3_idx"
            ),
        ),
    ]
